knife4j:
  enable: true
  openapi:
    title: demo测试
    description: "`demo测试**
    # aaa"
    email: katherine@foxmail.com
    concat: katherine
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: demo
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3
